'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Activity, Server, LayoutDashboard, Boxes, Globe2, Rocket, DatabaseBackup, HeartPulse, Bell, ChartNoAxesCombined, ScrollText, Users, Settings2, Search, Plus, ArrowUpRight, Cpu, MemoryStick, HardDrive, Command, CircleHelp, ChevronDown, Wifi, WifiOff, ShieldCheck, KeyRound} from 'lucide-react';
import {api} from '@/lib/api';
import type {ServerSummary} from '@clouddeck/shared';
type Org={id:string;name:string;role:string};
const demo:ServerSummary[]=[
  {id:'demo-1',name:'Production API',hostname:'prod-api-01',status:'online',lastSeenAt:new Date().toISOString(),cpuPercent:24,memoryPercent:52,diskPercent:61},
  {id:'demo-2',name:'Database-01',hostname:'db-01',status:'online',lastSeenAt:new Date().toISOString(),cpuPercent:18,memoryPercent:68,diskPercent:43},
  {id:'demo-3',name:'Worker-01',hostname:'worker-01',status:'offline',lastSeenAt:null,cpuPercent:0,memoryPercent:0,diskPercent:57},
  {id:'demo-4',name:'Staging',hostname:'stage-01',status:'online',lastSeenAt:new Date().toISOString(),cpuPercent:42,memoryPercent:34,diskPercent:29}
];
const nav=[{label:'WORKSPACE',items:[[LayoutDashboard,'Dashboard'],[Server,'Servers'],[Boxes,'Containers'],[Globe2,'Domains']]},{label:'OPERATIONS',items:[[Rocket,'Deployments'],[DatabaseBackup,'Backups'],[HeartPulse,'Health checks'],[Bell,'Alerts']]},{label:'OBSERVABILITY',items:[[ChartNoAxesCombined,'Metrics'],[ScrollText,'Logs']]},{label:'ORGANIZATION',items:[[Users,'Members'],[KeyRound,'Secrets'],[ShieldCheck,'Audit logs'],[Settings2,'Settings']]}] as const;
export default function Dashboard(){
  const router=useRouter(); const [servers,setServers]=useState<ServerSummary[]>(demo);const [org,setOrg]=useState<Org|null>(null);const [demoMode,setDemoMode]=useState(true);const [loading,setLoading]=useState(true);const [error,setError]=useState(''); const [pairing,setPairing]=useState(''); const [pairedServerId,setPairedServerId]=useState('');const [filter,setFilter]=useState('');const [openAlerts,setOpenAlerts]=useState(1);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&document.activeElement instanceof HTMLElement)document.activeElement.blur()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
  useEffect(()=>{let cancelled=false; (async()=>{try{const data=await api<{organizations:Org[]}>('/organizations');const selected=data.organizations[0];if(!selected)return;const [result,summary]=await Promise.all([api<{servers:ServerSummary[]}>(`/organizations/${selected.id}/servers`),api<{openAlerts:number}>(`/organizations/${selected.id}/dashboard`)]);if(!cancelled){setOrg(selected);setServers(result.servers);setOpenAlerts(summary.openAlerts);setDemoMode(false)}}catch{if(!cancelled){setDemoMode(true);setOpenAlerts(demo.filter(server=>server.status==='offline').length)}}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
  async function addServer(){if(!org){router.push('/login');return}const name=prompt('Server name');if(!name?.trim())return;try{const result=await api<{id:string;pairingToken:string}>('/servers',{method:'POST',body:JSON.stringify({organizationId:org.id,name:name.trim()})});setPairing(result.pairingToken);setPairedServerId(result.id);const rows=await api<{servers:ServerSummary[]}>(`/organizations/${org.id}/servers`);setServers(rows.servers)}catch(e){setError(e instanceof Error?e.message:'Unable to add server')}}
  const visible=servers.filter(s=>`${s.name} ${s.hostname??''}`.toLowerCase().includes(filter.toLowerCase())); const online=servers.filter(s=>s.status==='online').length; const offline=servers.filter(s=>s.status==='offline').length;
  const openGlobalSearch=()=>window.dispatchEvent(new Event('clouddeck:open-search'));
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Activity size={20}/></span>clouddeck<span className="brand-dot">.</span></div><div className="workspace"><span className="workspace-symbol">{org?.name[0]?.toUpperCase()??'C'}</span><span><strong>{org?.name??'Demo Workspace'}</strong><small>{org?`${org.role} workspace`:'Portfolio preview'}</small></span><ChevronDown size={15}/></div><nav>{nav.map(group=><section key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([Icon,label])=><button key={label} className={`nav-link ${label==='Dashboard'?'selected':''}`} title={label} onClick={()=>label==='Servers'?router.push('/servers'):label==='Containers'?router.push('/containers'):label==='Deployments'?router.push('/deployments'):label==='Backups'?router.push('/backups'):label==='Domains'?router.push('/domains'):label==='Health checks'?router.push('/health-checks'):label==='Alerts'?router.push('/alerts'):label==='Metrics'?router.push('/metrics'):label==='Logs'?router.push('/logs'):label==='Members'?router.push('/members'):label==='Secrets'?router.push('/secrets'):label==='Audit logs'?router.push('/audit-logs'):label==='Settings'?router.push('/security'):label!=='Dashboard'&&setError(`${label} is planned for a later phase.`)}><Icon size={17}/><span>{label}</span>{label==='Alerts'&&openAlerts>0&&<span className="nav-count">{openAlerts}</span>}</button>)}</section>)}</nav><div className="side-bottom"><div className="side-help"><CircleHelp size={17}/> Documentation <ArrowUpRight size={14}/></div><div className="profile"><span className="avatar">CD</span><span><strong>{org?'Workspace member':'Demo visitor'}</strong><small>{org?'Signed in':'Preview mode'}</small></span><ChevronDown size={14}/></div></div></aside>
  <main className="main"><header className="topbar"><div className="breadcrumbs">Workspace <span>/</span> <strong>Dashboard</strong></div><div className="top-actions"><button className="keyboard" aria-label="Open global search" onClick={openGlobalSearch}><Command size={13}/> K</button><button aria-label="Search" onClick={openGlobalSearch}><Search size={19}/></button><button aria-label="Notifications" onClick={()=>router.push('/notifications')}><Bell size={19}/></button><span className="top-avatar">CD</span></div></header><div className="content"><div className="page-head"><div><div className="eyebrow">OVERVIEW <span className="head-date">/ {new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</span></div><h1>Infrastructure overview</h1><p className="muted">Your servers and services at a glance.</p></div><button className="primary" onClick={addServer}><Plus size={17}/> Add server</button></div>
  {demoMode&&<div className="demo-banner"><div><strong>Explore CloudDeck in demo mode</strong><span>These four servers and their metrics are simulated for this preview.</span></div><button onClick={()=>router.push('/login')}>Connect your servers <ArrowUpRight size={15}/></button></div>}
  {pairing&&<div className="pair-banner"><strong>Pairing token — shown once, expires in 10 minutes</strong><code>Server ID: {pairedServerId}<br/>Pairing token: {pairing}</code><span>Install the Go agent, then set CLOUDDECK_SERVER_ID and CLOUDDECK_PAIRING_TOKEN. See docs/AGENT_PROTOCOL.md.</span><button onClick={()=>setPairing('')}>Dismiss</button></div>}
  {error&&<div className="notice" role="status">{error} <button onClick={()=>setError('')}>Dismiss</button></div>}
  <div className="section-title">Fleet health <span>LIVE STATUS</span></div><div className="stats"><Stat icon={<Server size={19}/>} label="Total servers" value={servers.length} sub="Across this workspace"/><Stat icon={<Wifi size={19}/>} label="Online" value={online} sub="Reporting normally" color="green"/><Stat icon={<WifiOff size={19}/>} label="Offline" value={offline} sub={offline?'Needs your attention':'All systems online'} color="red"/><Stat icon={<Bell size={19}/>} label="Open alerts" value={openAlerts} sub="Active incidents" color="amber"/></div>
  <div className="section-line"><div><h2>Servers</h2><p className="muted">Monitor and manage your infrastructure</p></div><div className="list-tools"><label className="search-box"><Search size={16}/><input id="server-filter" placeholder="Filter this server list..." value={filter} onChange={e=>setFilter(e.target.value)}/></label><span className="server-total">{visible.length} servers</span></div></div>
  <div className="server-grid">{visible.map(s=><article className="server-card" key={s.id}><div className="server-top"><div className="server-icon"><Server size={20}/></div><span className={`badge ${s.status}`}>● {s.status}</span></div><h3>{s.name}</h3><p className="hostname">{s.hostname??'Awaiting agent pairing'}</p><div className="card-divider"/><div className="metric-row"><span><Cpu size={15}/> CPU</span><strong>{s.cpuPercent??'—'}{s.cpuPercent==null?'':'%'}</strong></div><div className="meter"><i style={{width:`${s.cpuPercent??0}%`}}/></div><div className="metric-row"><span><MemoryStick size={15}/> Memory</span><strong>{s.memoryPercent??'—'}{s.memoryPercent==null?'':'%'}</strong></div><div className="meter"><i style={{width:`${s.memoryPercent??0}%`}}/></div><div className="metric-row"><span><HardDrive size={15}/> Disk</span><strong>{s.diskPercent??'—'}{s.diskPercent==null?'':'%'}</strong></div><div className="meter"><i style={{width:`${s.diskPercent??0}%`}}/></div><div className="card-footer"><span>{s.status==='online'?'● Reporting now':s.status==='pending'?'● Awaiting agent':'● Connection lost'}</span><button onClick={()=>router.push(`/servers/${s.id}`)}>View server <ArrowUpRight size={14}/></button></div></article>)}</div>
  {!visible.length&&<div className="empty">{loading?'Loading servers…':'No servers found. Add one to get started.'}</div>}
  <footer className="page-footer"><span>CloudDeck · Server operations in one place</span><span><span className="system-dot"/> Dashboard ready</span></footer></div></main></div>
}
function Stat({icon,label,value,sub,color='blue'}:{icon:React.ReactNode;label:string;value:number;sub:string;color?:string}){return <div className="stat"><div className={`stat-icon ${color}`}>{icon}</div><span className="stat-label">{label}</span><strong>{value.toString().padStart(2,'0')}</strong><span className="stat-sub">{sub}</span></div>}
