'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {ArrowLeft,Activity,Server,Cpu,MemoryStick,HardDrive,Network,Clock3,ShieldCheck} from 'lucide-react';
import {api} from '@/lib/api';
import {DockerPanel} from './docker-panel';
import {SystemdPanel} from './systemd-panel';
import {TerminalPanel} from './terminal-panel';
type ServerInfo={id:string;organization_id:string;name:string;hostname:string|null;provider:string|null;region:string|null;operating_system:string|null;architecture:string|null;agent_version:string|null;status:string;last_seen_at:string|null;tags:string[]};
type Point={bucket_at:string;cpu_percent:number;memory_percent:number;disk_percent:number;load_1:number;network_rx_bytes:number;network_tx_bytes:number};
const ranges=['1h','6h','24h','7d','30d'] as const;
export default function ServerPage(){const params=useParams<{id:string}>();const router=useRouter();const [server,setServer]=useState<ServerInfo|null>(null);const [points,setPoints]=useState<Point[]>([]);const [range,setRange]=useState<typeof ranges[number]>('24h');const [error,setError]=useState('');
 useEffect(()=>{if(params.id.startsWith('demo-')){const names:Record<string,string>={'demo-1':'Production API','demo-2':'Database-01','demo-3':'Worker-01','demo-4':'Staging'};const name=names[params.id];if(!name){setError('Demo server not found');return}setServer({id:params.id,organization_id:'demo',name,hostname:params.id+'-host',provider:'Demo',region:'Simulated',operating_system:'Ubuntu Linux',architecture:'arm64',agent_version:'demo',status:params.id==='demo-3'?'offline':'online',last_seen_at:new Date().toISOString(),tags:[]});setPoints(Array.from({length:60},(_,i)=>({bucket_at:new Date(Date.now()-(60-i)*60000).toISOString(),cpu_percent:20+Math.sin(i/5)*12+Math.sin(i/2)*5,memory_percent:50+Math.sin(i/9)*5,disk_percent:61,load_1:.8+Math.sin(i/6)*.3,network_rx_bytes:1000+i*50,network_tx_bytes:2000+i*70})));return}let active=true;const fetchData=async()=>{try{const [s,m]=await Promise.all([api<ServerInfo>(`/servers/${params.id}`),api<{points:Point[]}>(`/servers/${params.id}/metrics?range=${range}`)]);if(active){setServer(s);setPoints(m.points)}}catch(e){if(active)setError(e instanceof Error?e.message:'Unable to load server')}};fetchData();const timer=setInterval(fetchData,15000);return()=>{active=false;clearInterval(timer)}},[params.id,range]);
 const latest=points.at(-1);return <div className="detail-page"><div className="detail-nav"><button onClick={()=>router.push('/dashboard')}><ArrowLeft size={17}/> Dashboard</button><span className="detail-logo"><Activity size={18}/> clouddeck.</span></div>{error?<div className="notice">{error}</div>:!server?<div className="empty">Loading server…</div>:<main className="detail-content"><div className="detail-heading"><div><span className="eyebrow">INFRASTRUCTURE / SERVER {params.id.startsWith('demo-')?'· SIMULATED DATA':''}</span><h1>{server.name}</h1><p><span className={`badge ${server.status}`}>● {server.status}</span> {server.operating_system??'Operating system pending'} · {server.hostname??'Awaiting agent'}</p></div><span className="detail-id">ID {server.id}</span></div><div className="detail-stats"><div><Cpu size={19}/><small>CPU usage</small><strong>{latest?`${Number(latest.cpu_percent).toFixed(1)}%`:'—'}</strong></div><div><MemoryStick size={19}/><small>Memory</small><strong>{latest?`${Number(latest.memory_percent).toFixed(1)}%`:'—'}</strong></div><div><HardDrive size={19}/><small>Disk usage</small><strong>{latest?`${Number(latest.disk_percent).toFixed(1)}%`:'—'}</strong></div><div><Network size={19}/><small>Load average</small><strong>{latest?Number(latest.load_1).toFixed(2):'—'}</strong></div></div><section className="chart-card"><div className="chart-heading"><div><h2>System metrics</h2><p>One-minute aggregates · refreshed every 15 seconds</p></div><div className="range-tabs">{ranges.map(r=><button className={range===r?'active':''} key={r} onClick={()=>setRange(r)}>{r}</button>)}</div></div>{points.length?<><Chart points={points} keyName="cpu_percent" color="#4668e7"/><div className="chart-legend"><span>● CPU</span><span>● Memory</span><span>● Disk</span></div></>:<div className="chart-empty">No metrics yet. Pair the server agent to start receiving samples.</div>}</section><DockerPanel serverId={server.id} organizationId={server.organization_id} demo={params.id.startsWith('demo-')}/><SystemdPanel serverId={server.id} organizationId={server.organization_id} demo={params.id.startsWith('demo-')}/><TerminalPanel serverId={server.id} demo={params.id.startsWith('demo-')} online={server.status==='online'}/><div className="detail-bottom"><div><Server size={18}/><span>Provider</span><strong>{server.provider??'Not specified'}</strong></div><div><Clock3 size={18}/><span>Last seen</span><strong>{server.last_seen_at?new Date(server.last_seen_at).toLocaleString():'Never'}</strong></div><div><ShieldCheck size={18}/><span>Agent version</span><strong>{server.agent_version??'Not paired'}</strong></div></div></main>}</div>}
function Chart({points,keyName,color}:{points:Point[];keyName:'cpu_percent';color:string}){const trimmed=points.slice(-180);const coordinate=(key:'cpu_percent'|'memory_percent'|'disk_percent')=>trimmed.map((p,i)=>`${(i/Math.max(1,trimmed.length-1))*900},${180-Math.min(100,Math.max(0,Number(p[key])))*1.7}`).join(' ');return <svg className="chart-svg" role="img" aria-label="CPU, memory, and disk usage over time" viewBox="0 0 900 200" preserveAspectRatio="none"><path d="M0 10H900 M0 95H900 M0 180H900" stroke="#e9edf5" fill="none"/><polyline points={coordinate('disk_percent')} fill="none" stroke="#e5ad58" strokeWidth="2.5"/><polyline points={coordinate('memory_percent')} fill="none" stroke="#56bfa0" strokeWidth="2.5"/><polyline points={coordinate(keyName)} fill="none" stroke={color} strokeWidth="3"/></svg>}

