import nodemailer from 'nodemailer';

function mailTransport(){
  const host=process.env.SMTP_HOST;
  if(!host)throw new Error('SMTP_HOST is required for email delivery');
  return nodemailer.createTransport({
    host,
    port:Number(process.env.SMTP_PORT??587),
    secure:process.env.SMTP_SECURE==='true',
    auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined
  });
}

function sender(){
  return process.env.MAIL_FROM??'CloudDeck <noreply@localhost>';
}

export async function sendChallenge(kind:'verify_email'|'reset_password',email:string,token:string) {
  if (process.env.NODE_ENV==='test') return;
  const origin=process.env.APP_ORIGIN??'http://localhost:3000';
  const subject=kind==='verify_email'?'Verify your CloudDeck email':'Reset your CloudDeck password';
  const path=kind==='verify_email'?'verify':'reset-password';
  const link=`${origin}/${path}?token=${encodeURIComponent(token)}`;
  await mailTransport().sendMail({
    from:sender(),
    to:email,
    subject,
    text:`${subject}\n\nOpen this link within 30 minutes:\n${link}\n\nIf you did not request this, ignore this message.`
  });
}

export async function sendOperationalNotification(
  email:string,
  title:string,
  body:string|null,
  href:string|null
){
  if(process.env.NODE_ENV==='test')return;
  const origin=process.env.APP_ORIGIN??'http://localhost:3000';
  const safeTitle=title.replace(/[\r\n]+/g,' ').trim().slice(0,160)||'CloudDeck notification';
  const internalPath=href&&href.startsWith('/')&&!href.startsWith('//')?href:null;
  const link=internalPath?`${origin}${internalPath}`:null;
  const text=[
    safeTitle,
    body?.trim()||null,
    link?`Open in CloudDeck: ${link}`:null,
    'This message was generated by your CloudDeck workspace.'
  ].filter(Boolean).join('\n\n');
  await mailTransport().sendMail({
    from:sender(),
    to:email,
    subject:`[CloudDeck] ${safeTitle}`,
    text
  });
}
