import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildApp} from '../src/index.ts';
import {pool} from '../src/db.ts';
const app=buildApp();
test('registration, workspace isolation, server pairing, and refresh rotation',async()=>{
  await app.ready();
  const suffix=crypto.randomUUID();
  const register=await app.inject({method:'POST',url:'/api/v1/auth/register',payload:{email:`test-${suffix}@example.com`,password:'a secure passphrase 2026'}});
  assert.equal(register.statusCode,201,register.body);
  const data=register.json();
  const token=data.accessToken as string;
  const organizationId=data.organizationId as string;
  const cookie=register.cookies.find(c=>c.name==='clouddeck_refresh')?.value;
  assert.ok(cookie);
  const forbidden=await app.inject({method:'GET',url:`/api/v1/organizations/${crypto.randomUUID()}/servers`,headers:{authorization:`Bearer ${token}`}});
  assert.equal(forbidden.statusCode,403);
  const create=await app.inject({method:'POST',url:'/api/v1/servers',headers:{authorization:`Bearer ${token}`},payload:{organizationId,name:'Test server'}});
  assert.equal(create.statusCode,201,create.body);
  const server=create.json();
  const viewerRegister=await app.inject({method:'POST',url:'/api/v1/auth/register',payload:{email:`viewer-${suffix}@example.com`,password:'another secure passphrase 2026'}});
  assert.equal(viewerRegister.statusCode,201);
  const viewerUser=await pool.query('SELECT id FROM users WHERE email=$1',[`viewer-${suffix}@example.com`]);
  await pool.query('INSERT INTO organization_members(organization_id,user_id,role) VALUES($1,$2,$3)',[organizationId,viewerUser.rows[0].id,'viewer']);
  const viewerRestart=await app.inject({method:'POST',url:`/api/v1/servers/${server.id}/docker/containers/${'a'.repeat(64)}/action`,headers:{authorization:`Bearer ${viewerRegister.json().accessToken}`},payload:{action:'restart',confirm:true}});
  assert.equal(viewerRestart.statusCode,403);
  const pair=await app.inject({method:'POST',url:'/api/v1/agent/pair',payload:{serverId:server.id,token:server.pairingToken}});
  assert.equal(pair.statusCode,201,pair.body);
  const secondPair=await app.inject({method:'POST',url:'/api/v1/agent/pair',payload:{serverId:server.id,token:server.pairingToken}});
  assert.equal(secondPair.statusCode,401);
  const refreshed=await app.inject({method:'POST',url:'/api/v1/auth/refresh',headers:{cookie:`clouddeck_refresh=${cookie}`}});
  assert.equal(refreshed.statusCode,200,refreshed.body);
  const reused=await app.inject({method:'POST',url:'/api/v1/auth/refresh',headers:{cookie:`clouddeck_refresh=${cookie}`}});
  assert.equal(reused.statusCode,401);
  await pool.query('DELETE FROM users WHERE email IN ($1,$2)',[`test-${suffix}@example.com`,`viewer-${suffix}@example.com`]);
  await pool.query('DELETE FROM organizations WHERE id=$1',[organizationId]);
  await pool.query('DELETE FROM organizations WHERE id=$1',[viewerRegister.json().organizationId]);
  await app.close();
});
